# Generated by Django 3.2 on 2021-04-23 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='card_name',
            new_name='cardname',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='card_no',
            new_name='cardnumber',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='exp_mon',
            new_name='expmonth',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='exp_yr',
            new_name='expyear',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='full_name',
            new_name='fu',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='username',
            new_name='us',
        ),
    ]
