# Generated by Django 3.2 on 2021-04-23 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210423_1047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='expmonth',
            new_name='month',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='fu',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='us',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='expyear',
            new_name='year',
        ),
    ]
