# Generated by Django 3.2 on 2021-04-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210423_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cardname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='cardnumber',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='cvv',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='month',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='year',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='zip',
            field=models.CharField(max_length=5),
        ),
    ]
